FROM golang:1.22

WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o ./build/fizzbuzz.exe

#FROM scratch
FROM gcr.io/distroless/static-debian11

WORKDIR /usr/src/app

COPY --from=0 /usr/src/app/build/fizzbuzz.exe ./build/fizzbuzz.exe
COPY --from=0 /usr/src/app/templates/index.html ./templates/

CMD ["./build/fizzbuzz.exe", "serve"]