#FROM --platform=$BUILDPLATFORM  mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /source


COPY ./*.csproj .
RUN dotnet restore

COPY ./. .
RUN dotnet publish -c Release -o /out


#FROM mcr.microsoft.com/dotnet/nightly/aspnet:8.0-jammy-chiseled-composite
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

WORKDIR /out

COPY --from=build /out .

ENTRYPOINT ["dotnet", "MarketApi.dll"]